const data = {
  products: [
    {
      name: 'Camisa Nike',
      category: 'Camisas',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Camisa Adidas Fit',
      category: 'Camisas',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Camisa Lacoste',
      category: 'Camisas',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Calça Nike',
      category: 'Calças',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Calça Puma',
      category: 'Calças',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Calça Adidas',
      category: 'Calças',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'produto de alta qualidade',
    },
  ],
};
export default data;
