FROM debian
MAINTAINER Davi Josue Palmas "davipalmas@alunos.utfpr.edu.br"
RUN apt-get update
RUN apt-get install apache2 -y
RUN apt-get install apache2-utils -y
RUN apt-get install -y git
RUN apt-get clean

RUN echo "ServerName localhost" | tee /etc/apache2/conf-available/servername.conf
RUN a2enconf servername

ENV HTTPD_PREFIX /usr/local/apache2
ENV PATH $HTTPD_PREFIX/bin:$PATH

RUN ln -sf /dev/stdout /var/log/apache2/access.log
RUN ln -sf /dev/stderr /var/log/apache2/error.log

VOLUME ["/var/www", "/var/log/apache2", "/etc/apache2"]

COPY app/* /var/www/html

WORKDIR /var/www/html
RUN git clone https://github.com/dpalmas/tac.git

COPY app/* /var/www/html

EXPOSE 80

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
